### ISSUE TITLE
Globals still disabled - after permissions are fixed

### ISSUE THREAD

**Issue by joshstrange** [720kb/ndm#42] opened 2016-12-07 16:04 UTC
* OS: MacOS
* OS version: 10.12.1 (16B2555)
* Ndm version: 0.0.2-beta (0.0.2-beta)
* Node version: v6.5.0
* Npm version: 3.10.7
* Npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions): fixed
* Node installed via (brew, nvm, pkg, other ...): n (https://github.com/tj/n)
* How to replicate the bug/issue, if you know: Launch app, click "Enable", popup comes up asking me to fix permissions (I have), click "Done", app relaunches and "Enable" still shows and still gives the same message

**Comment by 45kb** [comment] 2016-12-07 16:22
@joshstrange Hi, thanks, it's a known big problem to test this, because on every machine is a different story unfortunately, just two questions for the moment:

- This works for you ```npm install -g <package>``` yes?

- Could you please check if any error or warning in DevTools console (OS Menu -> Debug)

If you find out what's going wrong then and tell us or just PR it, would be of super help.

**Comment by joshstrange** [comment] 2016-12-07 16:29
- This works for you npm install -g <package> yes?

Yes just did it with karma (with no sudo) and it worked (I've never installed karma before).


- Could you please check if any error or warning in DevTools console (OS Menu -> Debug)


```
Storage: OK
Global is disabled
```

I'll look through your code as I don't see anything odd happening.

**Comment by joshstrange** [comment] 2016-12-07 16:54
This appears to be due to the group id's not matching. @45kb Can you please tell me what the permissions are for you for `/usr/local` (the actual folder, not the stuff inside it). Also what the output of `npm config get prefix` is?

**Comment by gaharrington** [comment] 2016-12-07 16:58
I am having the same issue as @45kb.

`npm config get prefix`:
`/usr/local
`
permissions are for you for `/usr/local`:
`drwxr-xr-x    13 Greg  wheel    442 Oct 18 07:32 local
`

**Comment by 45kb** [comment] 2016-12-07 16:58
@joshstrange  :)

- ```npm config get prefix``` is `/Users/me/.npm-global`
- drwxr-xr-x  13 root  wheel  442  1 Nov 18:45 local/

**Comment by joshstrange** [comment] 2016-12-07 17:02
@45kb That's going to be the issue. Everyone who uses /use/local is probably not going to work right away. It may work if instead of checking group id we use user id and look at [prefix]/lib/node_modules instead of just [prefix]. I have the code pulled locally but I'm walking into a meeting, I can test some afterwards.

**Comment by 45kb** [comment] 2016-12-07 17:04
@joshstrange awesome! hope this is the definitive fix, run run no problems let me know as you are back around ;)

**Comment by JustinAiken** [comment] 2016-12-07 17:13
Another report if it helps:

```
$ sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
$ npm config get prefix
/usr/local
$   npm install -g leftpad
/usr/local/lib
└── leftpad@0.0.0
```

Same "enable" button behavior as OP

**Comment by 45kb** [comment] 2016-12-07 17:16
@JustinAiken   i actually tested on both my macs Sierra and El Captain, formatted many times the machines to test different envs and installers and node versions, to see what happens.

Everything works for me if i use nvm or node from node packager not if i install node from brew for example... (having fixed permissions ofc)

Need more accurated tests probably and feedbacks thanks for reporting!

**Comment by joshstrange** [comment] 2016-12-07 18:22
See my fix in #46

**Comment by 45kb** [comment] 2016-12-08 08:52
@gaharrington , @JustinAiken in case you have some time: could you try the @joshstrange fix? seems to work pretty good, here is the PR https://github.com/720kb/ndm/pull/46 or you can directly clone his fork https://github.com/joshstrange/ndm and just start the app from terminal (https://github.com/720kb/ndm#develop)

**Comment by JustinAiken** [comment] 2016-12-08 14:48
Tried out @joshstrange's fix, can confirm it fixed it for me 👍

**Comment by 45kb** [comment] 2016-12-08 15:32
@JustinAiken 👍

**Comment by gaharrington** [comment] 2016-12-08 16:37
@joshstrange I was not able to test this fix. 

I used the supplied directions (both `Build` & `Develop` sections), and see this when I launch ndm:


![image](https://cloud.githubusercontent.com/assets/3846592/21018316/a821ee78-bd29-11e6-824c-5f3e3092589a.png)

**Comment by 45kb** [comment] 2016-12-08 16:40
@gaharrington click OS menu -> ndm -> Debug see what's in devtools console 👍

**Comment by gaharrington** [comment] 2016-12-08 16:58
Ah, yes! Thanks for the tip! 

I see the issue, but I am not sure how to fix it:
`file://%27/Users/Greg/ndm/dist/js/index.js Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by gaharrington** [comment] 2016-12-08 17:28
I have fixed the `index.js` issue I just reported. (Wrong node version active. Grr...)

I have now successfully confirmed @joshstrange's fix! 👍

@joshstrange Thank you!!

**Comment by 45kb** [comment] 2016-12-08 17:34
@gaharrington thanks ! that's really nice to hear

**Comment by 45kb** [comment] 2016-12-10 11:13
Closing due https://github.com/720kb/ndm/pull/46 was merged, let's see in the next release what will happen, everythings seems ok now 🙏

**Closed by 45kb** 2016-12-10 11:13 UTC
Labels: Any Idea?, Feel free to PR, Known Problem, priority:1

**Comment by 45kb** [comment] 2016-12-12 08:06
So Beta-v3 is released and it includes this lovely fix by @joshstrange guys.
If you want you can download it from here https://720kb.github.io/ndm/

We are moving to an auto-updater soon, so sorry but for the moment the only way is to download a a complete new version of the app (just replace it).
